version: "3.8"

services:
    heritage-tracker:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        restart: unless-stopped
        container_name: heritage-tracker-app

    # Development service (optional)
    heritage-tracker-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3001:3000"
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        environment:
            - NODE_ENV=development
        restart: unless-stopped
        container_name: heritage-tracker-dev
        profiles:
            - dev
